package com.mrcoder20.portx.domain.usecase

import com.mrcoder20.portx.domain.model.ScanResult
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

class ExportReportUseCase {
    private val json = Json { 
        prettyPrint = true 
        ignoreUnknownKeys = true
    }

    operator fun invoke(scanResult: ScanResult, format: String = "JSON"): String {
        return when (format.uppercase()) {
            "CSV" -> {
                val sb = StringBuilder()
                sb.append("Port,Protocol,Service,Banner,State\n")
                scanResult.openPorts.forEach { port ->
                    val service = scanResult.portServices[port] ?: "unknown"
                    val banner = (scanResult.portBanners[port] ?: "").replace(",", ";")
                    sb.append("$port,TCP,$service,$banner,open\n")
                }
                sb.toString()
            }
            "MD" -> {
                val dateTime = kotlin.time.Instant.fromEpochMilliseconds(scanResult.timestamp)
                    .toLocalDateTime(TimeZone.currentSystemDefault())
                val sb = StringBuilder()
                sb.append("# PortX Scan Report\n\n")
                sb.append("## Summary\n")
                sb.append("- **Target:** `${scanResult.target}`\n")
                sb.append("- **Date:** ${dateTime.date} ${dateTime.time.hour}:${dateTime.time.minute}\n")
                sb.append("- **Security Score:** ${scanResult.securityScore}%\n")
                sb.append("- **Open Ports:** ${scanResult.openPorts.size}\n\n")
                
                sb.append("## Discovered Services\n")
                sb.append("| Port | Service | Banner |\n")
                sb.append("| --- | --- | --- |\n")
                scanResult.openPorts.sorted().forEach { port ->
                    val service = scanResult.portServices[port] ?: "unknown"
                    val banner = scanResult.portBanners[port] ?: "-"
                    sb.append("| `$port` | $service | $banner |\n")
                }
                sb.append("\n\n*Generated by PortX Professional Engine*")
                sb.toString()
            }
            else -> json.encodeToString(scanResult)
        }
    }
}
